In [ ]:
!pip install transformers datasets accelerate
!pip install -U bitsandbytes>=0.46.1

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
from google.colab import userdata
import os

hf_token = userdata.get('HF_TOKEN')
os.environ['HF_TOKEN'] = hf_token
print("HF_TOKEN loaded from Colab secrets and set as environment variable.")

HF_TOKEN loaded from Colab secrets and set as environment variable.

## Phase 1

In [ ]:
# ============================================================
# Phase 1: CinePile Text-Only Evaluation — Final Fix
# ============================================================

import gc
import torch
import pandas as pd
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    AutoModel,
    BitsAndBytesConfig
)
from tqdm import tqdm


# ============================================================
# 1. Configure Class
# ============================================================
@dataclass
class ExperimentConfig:
    dataset_name: str           = 'tomg-group-umd/cinepile'
    dataset_split: str          = 'test'
    max_samples: Optional[int]  = None

    max_scene_length: int       = 1500
    max_input_tokens: int       = 2048
    deberta_max_tokens: int     = 512

    max_new_tokens: int         = 5
    do_sample: bool             = False

    load_in_4bit: bool          = True
    bnb_4bit_quant_type: str    = "nf4"
    bnb_4bit_compute_dtype: torch.dtype = torch.bfloat16

    models: list = field(default_factory=lambda: [
        ('DeBERTa-v3-base', 'microsoft/deberta-v3-base',          'deberta'),
        ('Llama-3.1-8B',    'meta-llama/Llama-3.1-8B-Instruct',  'llm'),
        ('Mistral-7B',      'mistralai/Mistral-7B-Instruct-v0.3', 'llm'),
    ])

    output_csv: str = 'phase1_results.csv'

    category_map: dict = field(default_factory=lambda: {
        'TEMP': 'Temporal',
        'CRD':  'Character and',
        'NPA':  'Narrative and',
        'STA':  'Setting and',
        'TH':   'Theme Exploration',
    })

# ============================================================
# 2. Prepare dataset
# ============================================================
class CinePileDataset:

    LETTERS = ['A', 'B', 'C', 'D', 'E']

    def __init__(self, config: ExperimentConfig):
        self.config = config
        self.data   = self._load()

    @classmethod
    def _answer_text_to_letter(cls, answer_text: str, choices: list) -> str:


        for i, choice in enumerate(choices):
            if answer_text == choice:
                return cls.LETTERS[i]


        answer_stripped = answer_text.strip()
        for i, choice in enumerate(choices):
            if answer_stripped == choice.strip():
                return cls.LETTERS[i]

        for i, choice in enumerate(choices):
            if answer_stripped in choice or choice.strip() in answer_stripped:
                return cls.LETTERS[i]

        print(f"  [Warning] Cannot match answer_key to choices.")
        print(f"    answer_key : {repr(answer_text)}")
        print(f"    choices    : {choices}")
        return 'A'  # fallback

    @staticmethod
    def _normalize_hard_split(raw) -> bool:
        if isinstance(raw, bool):
            return raw
        return str(raw).strip().lower() == 'true'

    def _load(self):
        raw = load_dataset(
            self.config.dataset_name,
            split=self.config.dataset_split
        )
        samples = []
        unmatched = 0

        for ex in raw:
            choices    = ex['choices']
            answer_key = ex['answer_key']

            # answer_key
            letter = self._answer_text_to_letter(answer_key, choices)
            if letter == 'A' and answer_key != choices[0]:
                unmatched += 1

            samples.append({
                'movie_scene':       ex['movie_scene'],
                'question':          ex['question'],
                'choices':           choices,
                'answer_key':        letter,           # 'A'~'E'
                'answer_text':       answer_key,
                'question_category': ex['question_category'],
                'hard_split':        self._normalize_hard_split(ex['hard_split']),
            })

        if self.config.max_samples:
            samples = samples[:self.config.max_samples]

        print(f"[Dataset] Loaded {len(samples)} samples")
        print(f"          answer_key sample : "
              f"{repr(samples[0]['answer_text'])} → {samples[0]['answer_key']}")
        print(f"          hard_split sample : {samples[0]['hard_split']}")
        if unmatched > 0:
            print(f"  [Warning] {unmatched} samples fell back to 'A' "
                  f"(answer not matched in choices)")
        return samples

    def run_sanity_check(self, n: int = 5):
        print("\n=== Sanity Check ===")
        for i, s in enumerate(self.data[:n]):
            idx = ord(s['answer_key']) - 65
            matched_text = s['choices'][idx]
            match_ok = matched_text.strip() == s['answer_text'].strip()
            print(f"  [{i}] {s['answer_key']} → \"{matched_text}\"")
            print(f"       original: \"{s['answer_text']}\"  match={match_ok}")
        print()


# ============================================================
# 3. Base Evaluator
# ============================================================
class BaseEvaluator(ABC):
    def __init__(self, model_id: str, config: ExperimentConfig):
        self.model_id  = model_id
        self.config    = config
        self.model     = None
        self.tokenizer = None

    @abstractmethod
    def load_model(self): pass

    @abstractmethod
    def predict(self, sample: dict) -> str: pass

    def evaluate(self, data: list) -> pd.DataFrame:
        records = []
        for sample in tqdm(data, desc=f"  {self.model_id}"):
            pred = self.predict(sample)
            records.append({
                'pred':              pred,
                'label':             sample['answer_key'],
                'question_category': sample['question_category'],
                'hard_split':        sample['hard_split'],
            })
        return pd.DataFrame(records)

    def free_memory(self):
        if self.model is not None:
            del self.model
            self.model = None
        if self.tokenizer is not None:
            del self.tokenizer
            self.tokenizer = None
        gc.collect()
        torch.cuda.empty_cache()
        print(f"  [Memory freed] {self.model_id}")


# ============================================================
# 4. LLM Evaluator
# ============================================================
class LLMEvaluator(BaseEvaluator):
    def load_model(self):
        bnb_config = BitsAndBytesConfig(
            load_in_4bit              = self.config.load_in_4bit,
            bnb_4bit_use_double_quant = True,
            bnb_4bit_quant_type       = self.config.bnb_4bit_quant_type,
            bnb_4bit_compute_dtype    = self.config.bnb_4bit_compute_dtype,
        )
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_id,
            quantization_config=bnb_config,
            device_map="auto",
        )
        self.model.eval()
        print(f"  [Loaded] {self.model_id} (4-bit)")

    def _build_prompt(self, sample: dict) -> str:
        scene   = sample['movie_scene'][:self.config.max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample['choices'])
        )
        return (
            "You are watching a movie. Based on the scene description, "
            "answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            "Answer with only the letter (A, B, C, D, or E):"
        )

    def predict(self, sample: dict) -> str:
        prompt = self._build_prompt(sample)
        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.config.max_input_tokens,
        ).to(self.model.device)

        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=self.config.max_new_tokens,
                do_sample=self.config.do_sample,
                pad_token_id=self.tokenizer.eos_token_id,
            )

        decoded = self.tokenizer.decode(
            outputs[0][inputs['input_ids'].shape[1]:],
            skip_special_tokens=True,
        ).strip().upper()

        for char in decoded:
            if char in 'ABCDE':
                return char
        return 'A'  # fallback


# ============================================================
# 5. DeBERTa-v3 Evaluator
# ============================================================
class DeBERTaEvaluator(BaseEvaluator):

    def load_model(self):
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        self.model     = AutoModel.from_pretrained(self.model_id).to(
            'cuda' if torch.cuda.is_available() else 'cpu'
        )
        self.model.eval()
        print(f"  [Loaded] {self.model_id}")

    def _score(self, text_a: str, text_b: str) -> float:
        inputs = self.tokenizer(
            text_a, text_b,
            return_tensors='pt',
            truncation=True,
            max_length=self.config.deberta_max_tokens,
            padding=True,
        ).to(self.model.device)
        with torch.no_grad():
            cls_emb = self.model(**inputs).last_hidden_state[:, 0, :]
        return cls_emb.norm(dim=-1).item()

    def predict(self, sample: dict) -> str:
        scene_q = (
            f"{sample['question']} "
            f"{sample['movie_scene'][:self.config.deberta_max_tokens // 2]}"
        )
        scores = [self._score(scene_q, c) for c in sample['choices']]
        return chr(65 + scores.index(max(scores))) # 'A'~'E'


# ============================================================
# 6. Metrics calculation
# ============================================================
class MetricsCalculator:
    def __init__(self, config: ExperimentConfig):
        self.config = config

    def compute(self, df: pd.DataFrame) -> dict:
        metrics = {}
        correct = df['pred'] == df['label']

        metrics['Overall']   = correct.mean()
        metrics['Overall_n'] = len(df)

        for abbr, cat_name in self.config.category_map.items():
            mask = df['question_category'].str.contains(
                cat_name, case=False, na=False
            )
            n = int(mask.sum())
            metrics[abbr]        = correct[mask].mean() if n > 0 else None
            metrics[f'{abbr}_n'] = n

        hard_mask = df['hard_split'] == True
        n_hard    = int(hard_mask.sum())
        metrics['Hard']   = correct[hard_mask].mean() if n_hard > 0 else None
        metrics['Hard_n'] = n_hard

        return metrics


# ============================================================
# 7. Phase1 Runner
# ============================================================
class Phase1Runner:
    EVALUATOR_REGISTRY = {
        'llm':     LLMEvaluator,
        'deberta': DeBERTaEvaluator,
    }

    def __init__(self, config: ExperimentConfig):
        self.config       = config
        self.dataset      = CinePileDataset(config)
        self.metrics_calc = MetricsCalculator(config)
        self.all_metrics  = {}

        # 运行 sanity check，确认 answer_key 转换正确
        self.dataset.run_sanity_check(n=3)

    def run(self):
        print("="*60)
        print("PHASE 1: CinePile Text-Only Evaluation")
        print("="*60)

        for display_name, model_id, eval_type in self.config.models:
            print(f"\n>>> [{eval_type.upper()}] {display_name}")

            evaluator_cls = self.EVALUATOR_REGISTRY[eval_type]
            evaluator     = evaluator_cls(model_id, self.config)
            evaluator.load_model()

            results_df = evaluator.evaluate(self.dataset.data)

            metrics = self.metrics_calc.compute(results_df)
            self.all_metrics[display_name] = metrics

            hard_str = (f"{metrics['Hard']:.2%}"
                        if metrics.get('Hard') is not None else "N/A")
            print(f"  Overall: {metrics['Overall']:.2%}  "
                  f"| Hard: {hard_str}  "
                  f"| n={metrics['Overall_n']}")

            # Free memory after each model run
            evaluator.free_memory()

        self._display_and_save()

    def _display_and_save(self):
        display_cols = ['Overall', 'TEMP', 'CRD', 'NPA', 'STA', 'TH', 'Hard']
        rows = []
        for model_name, metrics in self.all_metrics.items():
            row = {'Model': model_name}
            for col in display_cols:
                val = metrics.get(col)
                n   = metrics.get(f'{col}_n', metrics.get('Overall_n', ''))
                row[col] = f"{val:.1%}(n={n})" if val is not None else 'N/A'
            rows.append(row)

        df = pd.DataFrame(rows)
        print("\n" + "="*60)
        print("FINAL RESULTS — CinePile Text-Only")
        print("="*60)
        print(df.to_string(index=False))
        df.to_csv(self.config.output_csv, index=False)
        print(f"\nSaved → {self.config.output_csv}")


if __name__ == '__main__':

    # config = ExperimentConfig(
    #     max_samples     = None,     # using None for all test datasets
    #     max_scene_length= 1500,
    #     load_in_4bit    = True,
    #     output_csv      = 'phase1_mistral_results.csv',
    #     models=[
    #         # ('DeBERTa-v3-base', 'microsoft/deberta-v3-base',          'deberta'),
    #         # ('Llama-3.1-8B',    'meta-llama/Llama-3.1-8B-Instruct',  'llm'),
    #         ('Mistral-7B',      'mistralai/Mistral-7B-Instruct-v0.3', 'llm'),
    #     ]
    # )

    config = ExperimentConfig(
        max_samples     = None,     # using None for all test datasets
        max_scene_length= 1500,
        load_in_4bit    = True,
        output_csv      = 'phase1_llama_results.csv',
        models=[
            ('DeBERTa-v3-base', 'microsoft/deberta-v3-base',          'deberta'),
            # ('Llama-3.1-8B',    'meta-llama/Llama-3.1-8B-Instruct',  'llm'),
            # ('Mistral-7B',      'mistralai/Mistral-7B-Instruct-v0.3', 'llm'),
        ]
    )

    runner = Phase1Runner(config)
    runner.run()

[Dataset] Loaded 4941 samples
          answer_key sample : 'From anxiety to excitement' → E
          hard_split sample : True

=== Sanity Check ===
  [0] E → "From anxiety to excitement"
       original: "From anxiety to excitement"  match=True
  [1] E → "Suggests next steps"
       original: "Suggests next steps"  match=True
  [2] D → "The rough foliage"
       original: "The rough foliage"  match=True

============================================================
PHASE 1: CinePile Text-Only Evaluation
============================================================

>>> [DEBERTA] DeBERTa-v3-base

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

DebertaV2Model LOAD REPORT from: microsoft/deberta-v3-base
Key                                     | Status     |  |
----------------------------------------+------------+--+-
mask_predictions.classifier.bias        | UNEXPECTED |  |
lm_predictions.lm_head.bias             | UNEXPECTED |  |
mask_predictions.LayerNorm.weight       | UNEXPECTED |  |
lm_predictions.lm_head.dense.weight     | UNEXPECTED |  |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |  |
mask_predictions.classifier.weight      | UNEXPECTED |  |
mask_predictions.LayerNorm.bias         | UNEXPECTED |  |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |  |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |  |
mask_predictions.dense.weight           | UNEXPECTED |  |
mask_predictions.dense.bias             | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

  [Loaded] microsoft/deberta-v3-base

  microsoft/deberta-v3-base: 100%|██████████| 4941/4941 [11:20<00:00,  7.26it/s]

  Overall: 21.72%  | Hard: 20.63%  | n=4941
  [Memory freed] microsoft/deberta-v3-base

============================================================
FINAL RESULTS — CinePile Text-Only
============================================================
          Model       Overall         TEMP           CRD          NPA           STA           TH         Hard
DeBERTa-v3-base 21.7%(n=4941) 20.8%(n=688) 21.9%(n=2068) 20.3%(n=463) 22.8%(n=1532) 17.9%(n=190) 20.6%(n=887)

Saved → phase1_llama_results.csv

In [ ]:
##  phase 1 results
'''
============================================================
FINAL RESULTS — CinePile Text-Only
============================================================
          Model       Overall         TEMP           CRD          NPA           STA           TH         Hard
DeBERTa-v3-base 21.7%(n=4941) 20.8%(n=688) 21.9%(n=2068) 20.3%(n=463) 22.8%(n=1532) 17.9%(n=190) 20.6%(n=887)

     Model       Overall         TEMP           CRD          NPA           STA           TH         Hard
Mistral-7B 55.2%(n=4941) 34.9%(n=688) 57.4%(n=2068) 55.7%(n=463) 61.6%(n=1532) 52.6%(n=190) 32.7%(n=887)


Model	           Overall	       TEMP	          CRD	         NPA	         STA	         TH	        Hard
Llama-3.1-8B	60.0%(n=4941)	40.3%(n=688)	62.3%(n=2068)	56.4%(n=463)	67.8%(n=1532)	53.2%(n=190)	38.8%(n=887)
'''

## Phase 2

In [ ]:
!pip install transformers datasets accelerate bitsandbytes peft trl pyreft

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (0.29.0)
Requirement already satisfied: pyreft in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.6.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: pyvene>=0.1.4 in /usr/local/lib/python3.12/dist-packages (from pyreft) (0.1.8)
Requirement already satisfied: protobuf>=3.20.0 in /usr/local/lib/python3.12/dist-packages (from pyreft) (5.29.6)
Requirement already satisfied: matplotlib>=3.7.4 in /usr/local/lib/python3.12/dist-packages (from pyreft) (3.10.0)
Requirement already satisfied: ipywidgets>=8.1.1 in /usr/local/lib/python3.12/dist-packages (from pyreft) (8.1.8)
Requirement already satisfied: plotnine>=0.12.4 in /usr/local/lib/python3.12/dist-packages (from pyreft) (0.14.5)
Requirement already satisfied: sentencepiece>=0.1.96 in /usr/local/lib/python3.12/dist-packages (from pyreft) (0.2.1)
Requirement already satisfied: evaluate>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from pyreft) (0.4.6)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (from pyreft) (0.25.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pyreft) (1.6.1)
Requirement already satisfied: jupyter in /usr/local/lib/python3.12/dist-packages (from pyreft) (1.1.1)
Requirement already satisfied: ydata-profiling>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from pyreft) (4.18.1)
Requirement already satisfied: seaborn==0.12.2 in /usr/local/lib/python3.12/dist-packages (from pyreft) (0.12.2)
Requirement already satisfied: gcsfs>=2024.2.0 in /usr/local/lib/python3.12/dist-packages (from pyreft) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: decorator>4.1.2 in /usr/local/lib/python3.12/dist-packages (from gcsfs>=2024.2.0->pyreft) (4.4.2)
Requirement already satisfied: google-auth>=1.2 in /usr/local/lib/python3.12/dist-packages (from gcsfs>=2024.2.0->pyreft) (2.47.0)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.12/dist-packages (from gcsfs>=2024.2.0->pyreft) (1.3.0)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.12/dist-packages (from gcsfs>=2024.2.0->pyreft) (3.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=8.1.1->pyreft) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=8.1.1->pyreft) (7.34.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=8.1.1->pyreft) (5.7.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=8.1.1->pyreft) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=8.1.1->pyreft) (3.0.16)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.4->pyreft) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: mizani~=0.13.0 in /usr/local/lib/python3.12/dist-packages (from plotnine>=0.12.4->pyreft) (0.13.5)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from plotnine>=0.12.4->pyreft) (1.16.3)
Requirement already satisfied: statsmodels>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from plotnine>=0.12.4->pyreft) (0.14.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.1)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (2.12.3)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.7.0->pyreft) (0.8.1)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (0.12.5)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (1.12)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling>=4.7.0->pyreft) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling>=4.7.0->pyreft) (1.9.0)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter->pyreft) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter->pyreft) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from jupyter->pyreft) (7.17.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from jupyter->pyreft) (6.17.1)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/dist-packages (from jupyter->pyreft) (4.5.6)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyreft) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pyreft) (3.6.0)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb->pyreft) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb->pyreft) (3.1.46)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb->pyreft) (4.9.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb->pyreft) (2.54.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb->pyreft) (4.0.12)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.2->gcsfs>=2024.2.0->pyreft) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=1.2->gcsfs>=2024.2.0->pyreft) (4.9.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (0.19.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=6.1.0->ipywidgets>=8.1.1->pyreft) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling>=4.7.0->pyreft) (0.43.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling>=4.7.0->pyreft) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling>=4.7.0->pyreft) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling>=4.7.0->pyreft) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.7.4->pyreft) (1.17.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.0->plotnine>=0.12.4->pyreft) (1.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling>=4.7.0->pyreft) (2.0.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib->gcsfs>=2024.2.0->pyreft) (2.0.0)

In [ ]:
from google.colab import userdata
import os

# Retrieve the HF_TOKEN from Colab secrets
hf_token = userdata.get('HF_TOKEN')

# Set it as an environment variable
os.environ['HF_TOKEN'] = hf_token

print("HF_TOKEN loaded from Colab secrets and set as environment variable.")
# Now, when load_dataset is called, it will automatically use this token for authentication.

HF_TOKEN loaded from Colab secrets and set as environment variable.

In [ ]:
# ============================================================
# Phase 2: PEFT Fine-tuning on CinePile (Text-Only)
# Methods: QLoRA, Prefix Tuning, ReFT (LoReFT)
# !pip install transformers datasets accelerate bitsandbytes peft trl pyreft
# ============================================================

import gc
import os
import torch
import pandas as pd
import numpy as np
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    BitsAndBytesConfig,
    DataCollatorWithPadding,
)
from peft import (
    LoraConfig,
    PrefixTuningConfig,
    get_peft_model,
    TaskType,
    PeftModel,
)
from trl import SFTTrainer, SFTConfig
from tqdm import tqdm


# ============================================================
# 1. Config
# ============================================================
@dataclass
class Phase2Config:
    # --- dataset ---
    dataset_name: str          = 'tomg-group-umd/cinepile'
    train_split: str           = 'train'
    test_split: str            = 'test'
    max_train_samples: Optional[int] = 2000
    max_test_samples: Optional[int]  = 500

    # --- base model---
    base_model_id: str         = 'meta-llama/Llama-3.1-8B-Instruct'

    # --- input ---
    max_scene_length: int      = 1000   #
    max_seq_length: int        = 1024   #

    # --- parameter for training ---
    num_train_epochs: int      = 2
    per_device_train_batch_size: int = 2
    gradient_accumulation_steps: int = 4   #  batch size = 8
    learning_rate: float       = 2e-4
    warmup_ratio: float        = 0.05
    lr_scheduler_type: str     = 'cosine'
    fp16: bool                 = False
    bf16: bool                 = True
    logging_steps: int         = 20
    save_steps: int            = 200
    output_base_dir: str       = './phase2_outputs'

    # --- QLoRA param ---
    lora_r: int                = 16
    lora_alpha: int            = 32
    lora_dropout: float        = 0.05
    lora_target_modules: list  = field(default_factory=lambda: [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ])

    # --- Prefix Tuning param ---
    prefix_num_virtual_tokens: int = 20

    # --- ReFT (LoReFT) param ---
    reft_rank: int             = 4
    reft_layers: list          = field(default_factory=lambda: [8, 16, 24])

    # --- evaluation ---
    max_new_tokens: int        = 5
    output_csv: str            = 'phase2_results.csv'

    # --- mapping: the same as Phase 1---
    category_map: dict = field(default_factory=lambda: {
        'TEMP': 'Temporal',
        'CRD':  'Character and',
        'NPA':  'Narrative and',
        'STA':  'Setting and',
        'TH':   'Theme Exploration',
    })


# ============================================================
# 2. Dataset
# ============================================================
class CinePileDataset:
    LETTERS = ['A', 'B', 'C', 'D', 'E']

    def __init__(self, config: Phase2Config):
        self.config = config
        self.train_data = self._load(config.train_split, config.max_train_samples)
        self.test_data  = self._load(config.test_split,  config.max_test_samples)
        print(f"[Dataset] Train: {len(self.train_data)} | Test: {len(self.test_data)}")

    @classmethod
    def _answer_text_to_letter(cls, answer_text: str, choices: list) -> str:
        for i, c in enumerate(choices):
            if answer_text.strip() == c.strip():
                return cls.LETTERS[i]
        for i, c in enumerate(choices):
            if answer_text.strip() in c or c.strip() in answer_text:
                return cls.LETTERS[i]
        return 'A'

    @staticmethod
    def _normalize_hard_split(raw) -> bool:
        if isinstance(raw, bool):
            return raw
        return str(raw).strip().lower() == 'true'

    def _load(self, split: str, max_samples: Optional[int]) -> list:
        raw = load_dataset(self.config.dataset_name, split=split)
        samples = []
        for ex in raw:
            letter = self._answer_text_to_letter(ex['answer_key'], ex['choices'])
            samples.append({
                'movie_scene':       ex['movie_scene'],
                'question':          ex['question'],
                'choices':           ex['choices'],
                'answer_key':        letter,
                'question_category': ex['question_category'],
                'hard_split':        self._normalize_hard_split(ex['hard_split']),
            })
        if max_samples:
            samples = samples[:max_samples]
        return samples


# ============================================================
# 3. Prompt
# ============================================================
class PromptBuilder:

    @staticmethod
    def build_train_prompt(sample: dict, max_scene_length: int) -> str:
        scene   = sample['movie_scene'][:max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample['choices'])
        )
        answer  = sample['answer_key']
        return (
            f"You are watching a movie. Based on the scene description, "
            f"answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            f"Answer: {answer}"   # with answer
        )

    @staticmethod
    def build_inference_prompt(sample: dict, max_scene_length: int) -> str:
        scene   = sample['movie_scene'][:max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample['choices'])
        )
        return (
            f"You are watching a movie. Based on the scene description, "
            f"answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            f"Answer:"   # without answer
        )


# ============================================================
# 4. Evaluator
# ============================================================
class Evaluator:
    def __init__(self, config: Phase2Config):
        self.config = config

    def evaluate(self, model, tokenizer, test_data: list,
                 method_name: str) -> dict:
        model.eval()
        records = []
        for sample in tqdm(test_data, desc=f"  Evaluating {method_name}"):
            pred = self._predict(model, tokenizer, sample)
            records.append({
                'pred':              pred,
                'label':             sample['answer_key'],
                'question_category': sample['question_category'],
                'hard_split':        sample['hard_split'],
            })
        df = pd.DataFrame(records)
        return self._compute_metrics(df)

    def _predict(self, model, tokenizer, sample: dict) -> str:
        prompt  = PromptBuilder.build_inference_prompt(
            sample, self.config.max_scene_length
        )
        inputs  = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.config.max_seq_length,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=self.config.max_new_tokens,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )
        decoded = tokenizer.decode(
            outputs[0][inputs['input_ids'].shape[1]:],
            skip_special_tokens=True,
        ).strip().upper()

        for char in decoded:
            if char in 'ABCDE':
                return char
        return 'A'

    def _compute_metrics(self, df: pd.DataFrame) -> dict:
        correct  = df['pred'] == df['label']
        metrics  = {
            'Overall':   correct.mean(),
            'Overall_n': len(df),
        }
        for abbr, keyword in self.config.category_map.items():
            mask = df['question_category'].str.contains(
                keyword, case=False, na=False
            )
            n = int(mask.sum())
            metrics[abbr]        = correct[mask].mean() if n > 0 else None
            metrics[f'{abbr}_n'] = n

        hard_mask    = df['hard_split'] == True
        n_hard       = int(hard_mask.sum())
        metrics['Hard']   = correct[hard_mask].mean() if n_hard > 0 else None
        metrics['Hard_n'] = n_hard
        return metrics


# ============================================================
# 5. Base Trainer
# ============================================================
class BasePEFTTrainer(ABC):
    def __init__(self, config: Phase2Config):
        self.config    = config
        self.model     = None
        self.tokenizer = None
        self.method_name = "base"

    def _load_base_model_4bit(self):
        """加载 4-bit 量化基础模型（QLoRA 用）"""
        bnb_config = BitsAndBytesConfig(
            load_in_4bit              = True,
            bnb_4bit_use_double_quant = True,
            bnb_4bit_quant_type       = "nf4",
            bnb_4bit_compute_dtype    = torch.bfloat16,
        )
        tokenizer = AutoTokenizer.from_pretrained(self.config.base_model_id)
        tokenizer.pad_token    = tokenizer.eos_token
        tokenizer.padding_side = "right"

        model = AutoModelForCausalLM.from_pretrained(
            self.config.base_model_id,
            quantization_config=bnb_config,
            device_map="auto",
        )
        return model, tokenizer

    def _load_base_model_bf16(self):
        """加载 bf16 基础模型（Prefix Tuning / ReFT 用）"""
        tokenizer = AutoTokenizer.from_pretrained(self.config.base_model_id)
        tokenizer.pad_token    = tokenizer.eos_token
        tokenizer.padding_side = "right"

        model = AutoModelForCausalLM.from_pretrained(
            self.config.base_model_id,
            torch_dtype=torch.bfloat16,
            device_map="auto",
        )
        return model, tokenizer

    def _make_hf_dataset(self, data: list):
        """将样本列表转为 HuggingFace Dataset（SFTTrainer 需要）"""
        from datasets import Dataset
        return Dataset.from_list([
            {'text': PromptBuilder.build_train_prompt(
                s, self.config.max_scene_length
            )}
            for s in data
        ])

    def _output_dir(self) -> str:
        path = os.path.join(self.config.output_base_dir, self.method_name)
        os.makedirs(path, exist_ok=True)
        return path

    def free_memory(self):
        if self.model is not None:
            del self.model
            self.model = None
        if self.tokenizer is not None:
            del self.tokenizer
            self.tokenizer = None
        gc.collect()
        torch.cuda.empty_cache()
        print(f"  [Memory freed] {self.method_name}")

    @abstractmethod
    def train(self, train_data: list): pass

    @abstractmethod
    def load_for_inference(self): pass


# ============================================================
# 6. QLoRA Trainer
# ============================================================
class QLoRATrainer(BasePEFTTrainer):

    def __init__(self, config: Phase2Config):
        super().__init__(config)
        self.method_name = f"qlora_r{config.lora_r}"

    def train(self, train_data: list):
        print(f"\n[QLoRA] Loading base model (4-bit)...")
        model, tokenizer = self._load_base_model_4bit()

        lora_config = LoraConfig(
            r                = self.config.lora_r,
            lora_alpha       = self.config.lora_alpha,
            lora_dropout     = self.config.lora_dropout,
            target_modules   = self.config.lora_target_modules,
            bias             = "none",
            task_type        = TaskType.CAUSAL_LM,
        )

        train_args = SFTConfig(
            output_dir                  = self._output_dir(),
            num_train_epochs            = self.config.num_train_epochs,
            per_device_train_batch_size = self.config.per_device_train_batch_size,
            gradient_accumulation_steps = self.config.gradient_accumulation_steps,
            learning_rate               = self.config.learning_rate,
            warmup_ratio                = self.config.warmup_ratio,
            lr_scheduler_type           = self.config.lr_scheduler_type,
            bf16                        = self.config.bf16,
            logging_steps               = self.config.logging_steps,
            save_steps                  = self.config.save_steps,
            max_seq_length              = self.config.max_seq_length,
            dataset_text_field          = "text",
            report_to                   = "none",
            gradient_checkpointing      = True,
            optim                       = "paged_adamw_8bit",
        )

        hf_dataset = self._make_hf_dataset(train_data)

        trainer = SFTTrainer(
            model         = model,
            args          = train_args,
            train_dataset = hf_dataset,
            peft_config   = lora_config,
            tokenizer     = tokenizer,
        )

        print(f"[QLoRA] Training... (samples={len(train_data)})")
        trainer.train()
        trainer.save_model(self._output_dir())
        tokenizer.save_pretrained(self._output_dir())
        print(f"[QLoRA] Saved → {self._output_dir()}")

        self.model     = trainer.model
        self.tokenizer = tokenizer

    def load_for_inference(self):
        """从保存的 checkpoint 加载用于推理"""
        print(f"[QLoRA] Loading from {self._output_dir()}")
        model, tokenizer = self._load_base_model_4bit()
        self.model     = PeftModel.from_pretrained(model, self._output_dir())
        self.tokenizer = tokenizer


# ============================================================
# 7. Prefix Tuning Trainer
# ============================================================
class PrefixTuningTrainer(BasePEFTTrainer):

    def __init__(self, config: Phase2Config):
        super().__init__(config)
        self.method_name = f"prefix_vt{config.prefix_num_virtual_tokens}"

    def train(self, train_data: list):
        print(f"\n[Prefix] Loading base model (bf16)...")
        model, tokenizer = self._load_base_model_bf16()

        prefix_config = PrefixTuningConfig(
            task_type          = TaskType.CAUSAL_LM,
            num_virtual_tokens = self.config.prefix_num_virtual_tokens,
            prefix_projection  = True,
        )

        model = get_peft_model(model, prefix_config)
        model.print_trainable_parameters()

        train_args = SFTConfig(
            output_dir                  = self._output_dir(),
            num_train_epochs            = self.config.num_train_epochs,
            per_device_train_batch_size = self.config.per_device_train_batch_size,
            gradient_accumulation_steps = self.config.gradient_accumulation_steps,
            learning_rate               = 5e-4,   # Prefix Tuning 需要更大 lr
            warmup_ratio                = self.config.warmup_ratio,
            lr_scheduler_type           = self.config.lr_scheduler_type,
            bf16                        = self.config.bf16,
            logging_steps               = self.config.logging_steps,
            save_steps                  = self.config.save_steps,
            max_seq_length              = self.config.max_seq_length,
            dataset_text_field          = "text",
            report_to                   = "none",
            gradient_checkpointing      = False,  # Prefix Tuning 不兼容 grad ckpt
        )

        hf_dataset = self._make_hf_dataset(train_data)

        trainer = SFTTrainer(
            model         = model,
            args          = train_args,
            train_dataset = hf_dataset,
            tokenizer     = tokenizer,
        )

        print(f"[Prefix] Training... (samples={len(train_data)})")
        trainer.train()
        trainer.save_model(self._output_dir())
        tokenizer.save_pretrained(self._output_dir())
        print(f"[Prefix] Saved → {self._output_dir()}")

        self.model     = model
        self.tokenizer = tokenizer

    def load_for_inference(self):
        print(f"[Prefix] Loading from {self._output_dir()}")
        model, tokenizer = self._load_base_model_bf16()
        self.model     = PeftModel.from_pretrained(model, self._output_dir())
        self.tokenizer = tokenizer


# ============================================================
# 8. ReFT (LoReFT) Trainer
# ============================================================
class ReFTTrainer(BasePEFTTrainer):

    def __init__(self, config: Phase2Config):
        super().__init__(config)
        self.method_name = f"reft_r{config.reft_rank}"

    def train(self, train_data: list):
        try:
            import pyreft
        except ImportError:
            print("[ReFT] pyreft not installed. Run: pip install pyreft")
            return

        print(f"\n[ReFT] Loading base model (bf16)...")
        model, tokenizer = self._load_base_model_bf16()

        reft_config = pyreft.ReftConfig(
            representations=[
                {
                    "layer"           : l,
                    "component"       : "block_output",
                    "low_rank_dimension": self.config.reft_rank,
                    "intervention"    : pyreft.LoreftIntervention(
                        embed_dim          = model.config.hidden_size,
                        low_rank_dimension = self.config.reft_rank,
                    )
                }
                for l in self.config.reft_layers
            ]
        )
        reft_model = pyreft.get_reft_model(model, reft_config)
        reft_model.print_trainable_parameters()

        train_dataset = self._make_reft_dataset(
            train_data, tokenizer, pyreft
        )

        training_args = TrainingArguments(
            output_dir                  = self._output_dir(),
            num_train_epochs            = self.config.num_train_epochs,
            per_device_train_batch_size = self.config.per_device_train_batch_size,
            gradient_accumulation_steps = self.config.gradient_accumulation_steps,
            learning_rate               = self.config.learning_rate,
            warmup_ratio                = self.config.warmup_ratio,
            bf16                        = self.config.bf16,
            logging_steps               = self.config.logging_steps,
            save_steps                  = self.config.save_steps,
            report_to                   = "none",
        )

        reft_trainer = pyreft.ReftTrainerForCausalLM(
            model         = reft_model,
            args          = training_args,
            train_dataset = train_dataset,
            tokenizer     = tokenizer,
            data_collator = pyreft.ReftDataCollator(
                data_collator=DataCollatorWithPadding(tokenizer)
            ),
        )

        print(f"[ReFT] Training... (samples={len(train_data)})")
        reft_trainer.train()
        reft_model.save(self._output_dir())
        tokenizer.save_pretrained(self._output_dir())
        print(f"[ReFT] Saved → {self._output_dir()}")

        self.model     = reft_model
        self.tokenizer = tokenizer

    def _make_reft_dataset(self, data, tokenizer, pyreft):

        from datasets import Dataset
        prompts, outputs = [], []
        for s in data:
            prompt = PromptBuilder.build_inference_prompt(
                s, self.config.max_scene_length
            )
            prompts.append(prompt)
            outputs.append(s['answer_key'])

        return pyreft.make_last_position_supervised_data_module(
            tokenizer     = tokenizer,
            model         = self.model,
            inputs        = prompts,
            outputs       = outputs,
            num_interventions = len(self.config.reft_layers),
        )

    def load_for_inference(self):
        try:
            import pyreft
        except ImportError:
            print("[ReFT] pyreft not installed.")
            return

        print(f"[ReFT] Loading from {self._output_dir()}")
        model, tokenizer = self._load_base_model_bf16()
        self.model     = pyreft.ReftModel.load(self._output_dir(), model)
        self.tokenizer = tokenizer


# ============================================================
# 9. Phase2
# ============================================================
class Phase2Runner:
    def __init__(self, config: Phase2Config):
        self.config      = config
        self.dataset     = CinePileDataset(config)
        self.evaluator   = Evaluator(config)
        self.all_metrics = {}


        self.trainers = [
            # QLoRATrainer(config),
            PrefixTuningTrainer(config),
            # ReFTTrainer(config),
        ]

    def run(self):
        print("\n" + "="*60)
        print("PHASE 2: PEFT Fine-tuning on CinePile")
        print(f"Base model : {self.config.base_model_id}")
        print(f"Train size : {len(self.dataset.train_data)}")
        print(f"Test size  : {len(self.dataset.test_data)}")
        print("="*60)

        for trainer in self.trainers:
            print(f"\n{'='*60}")
            print(f"Method: {trainer.method_name.upper()}")
            print(f"{'='*60}")


            trainer.train(self.dataset.train_data)


            if trainer.model is not None:
                metrics = self.evaluator.evaluate(
                    trainer.model,
                    trainer.tokenizer,
                    self.dataset.test_data,
                    trainer.method_name,
                )
                self.all_metrics[trainer.method_name] = metrics
                hard_str = (f"{metrics['Hard']:.2%}"
                            if metrics.get('Hard') is not None else "N/A")
                print(f"  Overall: {metrics['Overall']:.2%} "
                      f"| Hard: {hard_str}")


            trainer.free_memory()

        self._display_and_save()

    def _display_and_save(self):
        display_cols = ['Overall', 'TEMP', 'CRD', 'NPA', 'STA', 'TH', 'Hard']
        rows = []
        for method_name, metrics in self.all_metrics.items():
            row = {'Method': method_name}
            for col in display_cols:
                val = metrics.get(col)
                n   = metrics.get(f'{col}_n', metrics.get('Overall_n', ''))
                row[col] = f"{val:.1%}(n={n})" if val is not None else 'N/A'
            rows.append(row)

        df = pd.DataFrame(rows)
        print("\n" + "="*60)
        print("PHASE 2 FINAL RESULTS — CinePile PEFT Fine-tuning")
        print("="*60)
        print(df.to_string(index=False))
        df.to_csv(self.config.output_csv, index=False)
        print(f"\nSaved → {self.config.output_csv}")


# ============================================================
# 10. Main
# ============================================================
if __name__ == '__main__':

    config = Phase2Config(
        base_model_id        = 'meta-llama/Llama-3.1-8B-Instruct',
        max_train_samples    = 20,
        max_test_samples     = 500,
        num_train_epochs     = 2,
        lora_r               = 16,
        prefix_num_virtual_tokens = 20,
        reft_rank            = 4,
        reft_layers          = [8, 16, 24],
        output_base_dir      = './phase2_outputs',
        output_csv           = 'phase2_results.csv',
    )

    runner = Phase2Runner(config)
    runner.run()

README.md: 0.00B [00:00, ?B/s]

v2/train-00000-of-00003.parquet:   0%|          | 0.00/21.9M [00:00<?, ?B/s]

v2/train-00001-of-00003.parquet:   0%|          | 0.00/23.2M [00:00<?, ?B/s]

v2/train-00002-of-00003.parquet:   0%|          | 0.00/23.3M [00:00<?, ?B/s]

v2/test-00000-of-00001.parquet:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/298888 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/4941 [00:00<?, ? examples/s]

[Dataset] Train: 20 | Test: 500

============================================================
PHASE 2: PEFT Fine-tuning on CinePile
Base model : meta-llama/Llama-3.1-8B-Instruct
Train size : 20
Test size  : 500
============================================================

============================================================
Method: REFT_R4
============================================================
nnsight is not detected. Please install via 'pip install nnsight' for nnsight backend.

[ReFT] Loading base model (bf16)...

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

TypeError: 'LoreftIntervention' object is not subscriptable

### 2.3 Prefix Tuning

In [ ]:
!pip install transformers datasets accelerate
!pip install -U bitsandbytes>=0.46.1
!pip install trl

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Collecting trl
  Downloading trl-1.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.13.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.0)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.8.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.25.2)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.24.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (3.13.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.4.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)

In [ ]:
from google.colab import userdata
import os

# Retrieve the HF_TOKEN from Colab secrets
hf_token = userdata.get('HF_TOKEN')

# Set it as an environment variable
os.environ['HF_TOKEN'] = hf_token

print("HF_TOKEN loaded from Colab secrets and set as environment variable.")
# Now, when load_dataset is called, it will automatically use this token for authentication.

HF_TOKEN loaded from Colab secrets and set as environment variable.

#vt=20

In [ ]:
# ============================================================
# Prefix Tuning on CinePile (Phase 2)
#   - Stratified sampling on CinePile (category × hard)
#   - Only save Prefix adapter
#   - Track used sample_ids to avoid re-training on same samples
#   - Save training_log_history.csv for loss analysis
# Requirements:
#   pip install transformers datasets accelerate peft trl
# ============================================================

import os
import gc
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Set
from datetime import datetime
from collections import defaultdict

import torch
import pandas as pd
from datasets import load_dataset, Dataset
from tqdm import tqdm

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
)
from transformers.trainer_utils import set_seed

from peft import (
    PrefixTuningConfig,
    get_peft_model,
    TaskType,
)
from trl import SFTTrainer, SFTConfig


# ================= 1. 配置 =================

@dataclass
class PrefixConfig:
    dataset_name: str          = "tomg-group-umd/cinepile"
    train_split: str           = "train"
    test_split: str            = "test"

    max_train_samples: Optional[int] = 20000
    max_test_samples: Optional[int]  = None
    hard_oversample_ratio: float     = 1.5

    base_model_id: str         = "meta-llama/Llama-3.1-8B-Instruct"

    max_scene_length: int      = 1000
    max_seq_length: int        = 1024

    num_train_epochs: int      = 3
    per_device_train_batch_size: int = 4
    gradient_accumulation_steps: int = 4
    learning_rate: float       = 5e-4   # Prefix 通常 lr 稍大
    warmup_ratio: float        = 0.05
    lr_scheduler_type: str     = "cosine"
    bf16: bool                 = True
    logging_steps: int         = 50

    output_dir: str            = "./prefix_cinepile"
    log_path: str              = "./prefix_experiment_log.csv"

    prefix_num_virtual_tokens: int = 20

    max_new_tokens: int        = 5

    category_map: Dict[str, str] = field(default_factory=lambda: {
        "TEMP": "Temporal",
        "CRD":  "Character and",
        "NPA":  "Narrative and",
        "STA":  "Setting and",
        "TH":   "Theme Exploration",
    })

    seed: int                  = 42


# ================= 2. Stratified Sampler + 数据集 =================

class StratifiedSampler:
    def __init__(self, cfg: PrefixConfig):
        self.cfg = cfg

    def sample(self, data):
        if self.cfg.max_train_samples is None:
            print(f"[Sampler] Using full train split: {len(data)} samples")
            return data

        target = self.cfg.max_train_samples
        groups = defaultdict(list)

        for s in data:
            cat  = self._get_category_key(s["question_category"])
            hard = bool(s["hard_split"])
            groups[(cat, hard)].append(s)

        n_categories = len(set(k[0] for k in groups))
        base_quota   = target / (n_categories * (1 + self.cfg.hard_oversample_ratio))
        easy_q       = base_quota
        hard_q       = base_quota * self.cfg.hard_oversample_ratio

        sampled = []
        report  = []

        import random
        random.seed(self.cfg.seed)

        for (cat, hard), group in sorted(groups.items()):
            quota  = int(hard_q if hard else easy_q)
            n_take = min(quota, len(group))
            taken  = random.sample(group, n_take)
            sampled.extend(taken)
            report.append({
                "category":  cat,
                "hard":      hard,
                "available": len(group),
                "quota":     quota,
                "sampled":   n_take,
            })

        if len(sampled) < target:
            sampled_ids = set(id(s) for s in sampled)
            remaining   = [s for s in data if id(s) not in sampled_ids]
            extra = random.sample(
                remaining, min(target - len(sampled), len(remaining))
            )
            sampled.extend(extra)

        df = pd.DataFrame(report)
        print("\n[Sampler] ===== Stratified Sampling Report =====")
        print(df.to_string(index=False))
        print(f"[Sampler] Total sampled: {len(sampled)}")
        print("[Sampler] " + "=" * 60)
        return sampled

    def _get_category_key(self, cat_str: str) -> str:
        for abbr, kw in self.cfg.category_map.items():
            if kw.lower() in cat_str.lower():
                return abbr
        return "OTHER"


class CinePileDataset:
    LETTERS = ["A", "B", "C", "D", "E"]

    def __init__(self, cfg: PrefixConfig, seen_ids: Optional[Set[int]] = None):
        self.cfg      = cfg
        self.seen_ids = seen_ids or set()
        self.train_data, self.test_data = self._load_all()
        print(f"[Dataset] Train: {len(self.train_data)} | Test: {len(self.test_data)}")

    @classmethod
    def _answer_text_to_letter(cls, answer_text: str, choices: list) -> str:
        for i, c in enumerate(choices):
            if answer_text.strip() == c.strip():
                return cls.LETTERS[i]
        for i, c in enumerate(choices):
            if answer_text.strip() in c or c.strip() in answer_text:
                return cls.LETTERS[i]
        return "A"

    @staticmethod
    def _normalize_hard_split(raw) -> bool:
        if isinstance(raw, bool):
            return raw
        return str(raw).strip().lower() == "true"

    def _load_split(self, split: str):
        raw = load_dataset(self.cfg.dataset_name, split=split)
        samples = []
        for idx, ex in enumerate(raw):
            letter = self._answer_text_to_letter(ex["answer_key"], ex["choices"])
            samples.append({
                "sample_id":         idx,
                "movie_scene":       ex["movie_scene"],
                "question":          ex["question"],
                "choices":           ex["choices"],
                "answer_key":        letter,
                "question_category": ex["question_category"],
                "hard_split":        self._normalize_hard_split(ex["hard_split"]),
            })
        return samples

    def _load_all(self):
        train_raw = self._load_split(self.cfg.train_split)
        test_raw  = self._load_split(self.cfg.test_split)

        if self.seen_ids:
            before = len(train_raw)
            train_raw = [s for s in train_raw if s["sample_id"] not in self.seen_ids]
            print(f"[Dataset] Filtered seen samples: {before} → {len(train_raw)}")

        sampler    = StratifiedSampler(self.cfg)
        train_data = sampler.sample(train_raw)

        if self.cfg.max_test_samples:
            test_data = test_raw[:self.cfg.max_test_samples]
        else:
            test_data = test_raw

        return train_data, test_data


# ================= 3. Prompt 与评估 =================

class PromptBuilder:
    @staticmethod
    def build_train_prompt(sample: dict, max_scene_length: int) -> str:
        scene   = sample["movie_scene"][:max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample["choices"])
        )
        return (
            "You are watching a movie. Based on the scene description, "
            "answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            f"Answer: {sample['answer_key']}"
        )

    @staticmethod
    def build_inference_prompt(sample: dict, max_scene_length: int) -> str:
        scene   = sample["movie_scene"][:max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample["choices"])
        )
        return (
            "You are watching a movie. Based on the scene description, "
            "answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            "Answer:"
        )


class Evaluator:
    def __init__(self, cfg: PrefixConfig):
        self.cfg = cfg

    def evaluate(self, model, tokenizer, test_data: list) -> dict:
        model.eval()
        device = next(model.parameters()).device
        records = []
        for s in tqdm(test_data, desc="Eval Prefix"):
            pred = self._predict(model, tokenizer, s, device)
            records.append({
                "pred":              pred,
                "label":             s["answer_key"],
                "question_category": s["question_category"],
                "hard_split":        s["hard_split"],
            })
        df = pd.DataFrame(records)
        return self._compute_metrics(df)

    def _predict(self, model, tokenizer, sample: dict, device: torch.device) -> str:
        prompt = PromptBuilder.build_inference_prompt(sample, self.cfg.max_scene_length)
        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.cfg.max_seq_length,
        ).to(device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=self.cfg.max_new_tokens,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )
        decoded = tokenizer.decode(
            outputs[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True,
        ).strip().upper()

        for ch in decoded:
            if ch in "ABCDE":
                return ch
        return "A"

    def _compute_metrics(self, df: pd.DataFrame) -> dict:
        correct = df["pred"] == df["label"]
        metrics = {"Overall": correct.mean(), "Overall_n": len(df)}
        for abbr, keyword in self.cfg.category_map.items():
            mask = df["question_category"].str.contains(keyword, case=False, na=False)
            n    = int(mask.sum())
            metrics[abbr]        = correct[mask].mean() if n > 0 else None
            metrics[f"{abbr}_n"] = n
        hard_mask = df["hard_split"] == True
        n_hard    = int(hard_mask.sum())
        metrics["Hard"]   = correct[hard_mask].mean() if n_hard > 0 else None
        metrics["Hard_n"] = n_hard
        return metrics


# ================= 4. Prefix Trainer =================

class PrefixTrainer:
    def __init__(self, cfg: PrefixConfig):
        self.cfg       = cfg
        self.model     = None
        self.tokenizer = None

    def _output_dir(self) -> str:
        os.makedirs(self.cfg.output_dir, exist_ok=True)
        return self.cfg.output_dir

    def _make_hf_dataset(self, data: list) -> Dataset:
        return Dataset.from_list([
            {"text": PromptBuilder.build_train_prompt(s, self.cfg.max_scene_length)}
            for s in data
        ])

    def _load_base_model_bf16(self):
        tokenizer = AutoTokenizer.from_pretrained(self.cfg.base_model_id)
        tokenizer.pad_token    = tokenizer.eos_token
        tokenizer.padding_side = "right"
        model = AutoModelForCausalLM.from_pretrained(
            self.cfg.base_model_id,
            torch_dtype=torch.bfloat16,
            device_map="auto",
        )
        return model, tokenizer

    def train(self, train_data: list):
        print(f"\n[Prefix] Loading base model (bf16)...")
        model, tokenizer = self._load_base_model_bf16()

        prefix_config = PrefixTuningConfig(
            task_type          = TaskType.CAUSAL_LM,
            num_virtual_tokens = self.cfg.prefix_num_virtual_tokens,
            prefix_projection  = True,
        )
        model = get_peft_model(model, prefix_config)
        model.print_trainable_parameters()

        args = SFTConfig(
            output_dir                  = self._output_dir(),
            num_train_epochs            = self.cfg.num_train_epochs,
            per_device_train_batch_size = self.cfg.per_device_train_batch_size,
            gradient_accumulation_steps = self.cfg.gradient_accumulation_steps,
            learning_rate               = self.cfg.learning_rate,
            warmup_ratio                = self.cfg.warmup_ratio,
            lr_scheduler_type           = self.cfg.lr_scheduler_type,
            bf16                        = self.cfg.bf16,
            logging_steps               = self.cfg.logging_steps,
            save_strategy               = "no",
            max_length                  = self.cfg.max_seq_length,
            dataset_text_field          = "text",
            report_to                   = "none",
            gradient_checkpointing      = False,
        )

        hf_dataset = self._make_hf_dataset(train_data)
        trainer = SFTTrainer(
            model            = model,
            args             = args,
            train_dataset    = hf_dataset,
            processing_class = tokenizer,
        )

        print(f"[Prefix] Training on {len(train_data)} samples...")
        trainer.train()

        log_history = trainer.state.log_history
        if len(log_history) > 0:
            df_log  = pd.DataFrame(log_history)
            log_path = os.path.join(self._output_dir(), "training_log_history.csv")
            df_log.to_csv(log_path, index=False)
            print(f"[Prefix] Step-wise log saved → {log_path}")

        trainer.save_model(self._output_dir())
        tokenizer.save_pretrained(self._output_dir())
        print(f"[Prefix] Saved adapter → {self._output_dir()}")

        self.model     = trainer.model
        self.tokenizer = tokenizer

    def free_memory(self):
        if self.model is not None:
            del self.model
        if self.tokenizer is not None:
            del self.tokenizer
        self.model = None
        self.tokenizer = None
        gc.collect()
        torch.cuda.empty_cache()


# ================= 5. 入口（含 used_ids） =================

if __name__ == "__main__":
    import transformers
    print("transformers:", transformers.__version__)

    from google.colab import drive
    drive.mount('/content/drive')

    import os
    PROJECT_DIR = "/content/drive/MyDrive/266_final/phase2/CinePile_Prefix"
    os.makedirs(PROJECT_DIR, exist_ok=True)
    print("Project dir:", PROJECT_DIR)

    cfg = PrefixConfig(
        base_model_id         = "meta-llama/Llama-3.1-8B-Instruct",
        max_train_samples     = 30000,
        max_test_samples      = None,
        hard_oversample_ratio = 1.5,
        num_train_epochs      = 3,
        per_device_train_batch_size = 4,
        gradient_accumulation_steps = 4,
        learning_rate         = 5e-4,
        output_dir            = os.path.join(PROJECT_DIR, "prefix_cinepile"),
        log_path              = os.path.join(PROJECT_DIR, "prefix_experiment_log.csv"),
    )

    used_ids_path = os.path.join(PROJECT_DIR, "used_sample_ids_prefix.txt")

    set_seed(cfg.seed)

    # 读取已用 sample_ids
    seen_ids: Set[int] = set()
    if os.path.exists(used_ids_path):
        with open(used_ids_path, "r") as f:
            for line in f:
                try:
                    seen_ids.add(int(line.strip()))
                except:
                    pass
        print(f"[UsedIDs] Prefix loaded {len(seen_ids)} seen ids from {used_ids_path}")

    dataset   = CinePileDataset(cfg, seen_ids=seen_ids)
    evaluator = Evaluator(cfg)
    trainer   = PrefixTrainer(cfg)

    trainer.train(dataset.train_data)
    metrics = evaluator.evaluate(trainer.model, trainer.tokenizer, dataset.test_data)

    print("\n[Prefix] ===== Eval Metrics =====")
    for k, v in metrics.items():
        if not k.endswith("_n") and v is not None:
            n = metrics.get(f"{k}_n", "")
            print(f"  {k:<10}: {v:.2%}  (n={n})")

    pd.DataFrame([metrics]).to_csv(
        os.path.join(cfg.output_dir, "prefix_metrics.csv"), index=False
    )

    # 记录本轮使用的 sample_id
    with open(used_ids_path, "a") as f:
        for s in dataset.train_data:
            f.write(str(s["sample_id"]) + "\n")
    print(f"[UsedIDs] Prefix appended {len(dataset.train_data)} ids → {used_ids_path}")

    trainer.free_memory()

transformers: 5.0.0
Mounted at /content/drive
Project dir: /content/drive/MyDrive/266_final/phase2/CinePile_Prefix
[UsedIDs] Prefix loaded 30000 seen ids from /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/used_sample_ids_prefix.txt

README.md: 0.00B [00:00, ?B/s]

v2/train-00000-of-00003.parquet:   0%|          | 0.00/21.9M [00:00<?, ?B/s]

v2/train-00001-of-00003.parquet:   0%|          | 0.00/23.2M [00:00<?, ?B/s]

v2/train-00002-of-00003.parquet:   0%|          | 0.00/23.3M [00:00<?, ?B/s]

v2/test-00000-of-00001.parquet:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/298888 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/4941 [00:00<?, ? examples/s]

[Dataset] Filtered seen samples: 298888 → 268888

[Sampler] ===== Stratified Sampling Report =====
category  hard  available  quota  sampled
     CRD False     117283   2400     2400
     NPA False      27972   2400     2400
     STA False      77952   2400     2400
    TEMP False      36616   2400     2400
      TH False       9065   2400     2400
[Sampler] Total sampled: 30000
[Sampler] ============================================================
[Dataset] Train: 30000 | Test: 4941

[Prefix] Loading base model (bf16)...

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 68,244,480 || all params: 8,098,505,728 || trainable%: 0.8427

Adding EOS to train dataset:   0%|          | 0/30000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/30000 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/30000 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 128009}.

[Prefix] Training on 30000 samples...

[Prefix] Step-wise log saved → /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/prefix_cinepile/training_log_history.csv
[Prefix] Saved adapter → /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/prefix_cinepile

Eval Prefix:   0%|          | 0/4941 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
/usr/local/lib/python3.12/dist-packages/peft/peft_model.py:2141: UserWarning: Position ids are not supported for parameter efficient tuning. Ignoring position ids.
  warnings.warn("Position ids are not supported for parameter efficient tuning. Ignoring position ids.")
Eval Prefix: 100%|██████████| 4941/4941 [07:24<00:00, 11.10it/s]

[Prefix] ===== Eval Metrics =====
  Overall   : 61.75%  (n=4941)
  TEMP      : 45.06%  (n=688)
  CRD       : 63.64%  (n=2068)
  NPA       : 64.15%  (n=463)
  STA       : 65.73%  (n=1532)
  TH        : 63.68%  (n=190)
  Hard      : 41.49%  (n=887)
[UsedIDs] Prefix appended 30000 ids → /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/used_sample_ids_prefix.txt

In [ ]:
from datasets import load_dataset

dataset = load_dataset('tomg-group-umd/cinepile', split='test')

# 查看前20个 answer_key 的原始值
print("=== 前20个 answer_key ===")
for i in range(20):
    ak = dataset[i]['answer_key']
    print(f"  [{i}] type={type(ak).__name__}, value={repr(ak)}")

# 查看所有唯一值
print("\n=== 所有唯一 answer_key 值（完整测试集）===")
from collections import Counter
counter = Counter(str(dataset[i]['answer_key']) for i in range(len(dataset)))
for val, cnt in sorted(counter.items()):
    print(f"  {repr(val):10s} → {cnt} 条")

=== 前20个 answer_key ===
  [0] type=str, value='From anxiety to excitement'
  [1] type=str, value='Suggests next steps'
  [2] type=str, value='The rough foliage'
  [3] type=str, value='She closes her eyes and focuses on staying calm without moving at all.'
  [4] type=str, value='Rough and dense'
  [5] type=str, value='They hear an aircraft approaching.'
  [6] type=str, value='To reach a specific location'
  [7] type=str, value='They become more confident'
  [8] type=str, value='The sound of a helicopter approaching'
  [9] type=str, value='Reed'
  [10] type=str, value='The sound of a helicopter'
  [11] type=str, value='In a rocky plateau'
  [12] type=str, value='It is a valley with spots of light'
  [13] type=str, value='They use a thermal suit'
  [14] type=str, value='They are trying to remain undetected by the helicopter using thermal suits.'
  [15] type=str, value='It illuminates the surrounding foliage.'
  [16] type=str, value='Directly underneath'
  [17] type=str, value='Colleagues'
  [18] type=str, value='It slithers between her thighs'
  [19] type=str, value='Reed says "I got it," Darren moves behind Reed, Darren observes the broken sensor.'

=== 所有唯一 answer_key 值（完整测试集）===
  '"Delegation arrived this morning."' → 1 条
  '"Dr. Watson, I have always been taken by your unwavering devotion to Mr. Holmes."' → 1 条
  '"Goodbye."' → 1 条
  '"Hi, friend"' → 1 条
  '"How extraordinary."' → 1 条
  '"I knew that."' → 1 条
  '"I think we\'re gonna need more toilet paper."' → 1 条
  '"Nothing. Nothing. I\'m fine."' → 1 条
  '"You remind me of my old butler."' → 1 条
  '0'        → 2 条
  '1'        → 34 条
  '1,000 square miles' → 1 条
  '100%'     → 1 条
  '15'       → 1 条
  '2'        → 41 条
  '3'        → 12 条
  '4'        → 5 条
  '5'        → 3 条
  'A $1 bill featuring a duck in place of George Washington.' → 1 条
  "A $1 bill with George Washington's portrait" → 1 条
  'A Ouija board' → 1 条
  'A Rolex watch' → 2 条
  'A bad trip' → 2 条
  'A baton'  → 1 条
  'A bazooka made from a bicycle' → 2 条
  'A beaver DJ.' → 1 条
  'A bedroom' → 1 条
  'A belt'   → 1 条
  'A blonde girl with her mouth sewn shut' → 1 条
  'A bomb exploding' → 1 条
  'A bottle' → 1 条
  'A box'    → 1 条
  'A bright blur' → 2 条
  'A bright blur moves across the room.' → 1 条
  'A bright blur moves through the shot.' → 2 条
  'A broken wire' → 1 条
  'A broomstick' → 1 条
  'A broomstick - to fly away' → 1 条
  'A buckle' → 1 条
  'A camera' → 1 条
  'A cane'   → 3 条
  'A cape.'  → 1 条
  'A car and money' → 1 条
  'A cat'    → 2 条
  'A cell phone' → 1 条
  'A cell phone.' → 1 条
  'A chair'  → 2 条
  'A chaotic and dangerous environment.' → 1 条
  'A character from a TV show' → 1 条
  'A childlike creature' → 1 条
  'A cicada' → 3 条
  'A cigarette' → 3 条
  'A cigarette lighter' → 1 条
  'A cinder block' → 2 条
  'A city street' → 1 条
  'A coat rack with a plastic garment bag' → 1 条
  'A cold chill' → 1 条
  'A comb'   → 1 条
  'A compliment on her skin.' → 1 条
  'A cool box' → 1 条
  'A courtesy gesture' → 1 条
  'A cricket bat' → 1 条
  'A cup'    → 1 条
  'A cup of tea' → 1 条
  'A curling iron' → 1 条
  'A cut'    → 1 条
  'A dance stage' → 1 条
  'A dark city skyline' → 1 条
  'A decision to end the friendship.' → 1 条
  'A demon'  → 1 条
  'A desert road.' → 1 条
  'A difference in values' → 1 条
  'A dining room' → 1 条
  'A discussion about becoming co-detectives.' → 1 条
  'A dog'    → 1 条
  'A dog running towards him' → 1 条
  'A dollar bill' → 1 条
  'A donkey' → 1 条
  'A dreamcatcher' → 1 条
  'A drink'  → 4 条
  'A duck'   → 1 条
  'A fear of abandonment' → 1 条
  'A fight at the club' → 1 条
  'A flame punch' → 1 条
  'A flaming baton to entertain the visitors.' → 1 条
  'A flaming baton.' → 1 条
  'A flash of Evelyn from a video' → 1 条
  'A flash of Evelyn from the video' → 1 条
  'A flashback' → 1 条
  'A flashlight' → 1 条
  'A flyer.' → 1 条
  'A food container' → 1 条
  'A framed photograph on the wall' → 1 条
  'A friend being attacked' → 1 条
  'A fruit'  → 1 条
  'A gas mask' → 1 条
  'A gate'   → 1 条
  'A ghost'  → 1 条
  'A gift box' → 3 条
  'A girl with her mouth sewn shut and hollow eyes' → 1 条
  'A glass of sparkling wine.' → 1 条
  'A glider' → 1 条
  'A glimpse of a dark hallway is shown.' → 1 条
  'A gloved hand switches off the ceiling light.' → 1 条
  'A glue grenade launcher' → 1 条
  'A gold ring' → 1 条
  'A gold ring in the cake.' → 1 条
  'A gold ring.' → 2 条
  'A golf club' → 1 条
  'A goofy dance' → 1 条
  'A greeting' → 1 条
  'A grin'   → 1 条
  'A group of footfallers, a donkey, and men in white bathrobes' → 1 条
  "A guard's exclamation" → 1 条
  'A guitar' → 1 条
  'A gun'    → 1 条
  'A hall'   → 1 条
  'A hamster' → 2 条
  'A hanging stage prop' → 1 条
  'A heated argument' → 1 条
  'A heavy-duty metal door slides open.' → 1 条
  'A human'  → 1 条
  'A kettledrum' → 1 条
  'A keychain' → 2 条
  'A keychain with a picture of Seattle' → 1 条
  'A knife'  → 1 条
  'A lamp'   → 1 条
  'A leak of classified information' → 1 条
  'A leopard print cape' → 1 条
  'A light'  → 1 条
  'A lighter' → 3 条
  "A lighty brick falls on Jack's wife." → 1 条
  'A manila envelope' → 1 条
  'A masked man' → 1 条
  'A meeting place for the Infidel Motorcycle Club' → 1 条
  'A mention of Abraham Lincoln Elementary' → 1 条
  'A message' → 1 条
  'A mirror' → 1 条
  'A moon'   → 1 条
  'A mouse'  → 1 条
  'A mummified corpse' → 1 条
  'A negotiator.' → 1 条
  'A newspaper' → 1 条
  'A painting.' → 1 条
  'A pair of sunglasses' → 2 条
  'A partnership in his business.' → 1 条
  'A patient' → 1 条
  'A patient in the house' → 1 条
  'A penthouse' → 1 条
  'A person' → 1 条
  'A phone'  → 3 条
  'A photograph of Howard with his parents' → 1 条
  'A photograph of a blonde woman in a leopard coat' → 1 条
  'A photograph of a known suspect' → 1 条
  'A pie tin sticks to his face.' → 1 条
  'A piece of fruit.' → 1 条
  "A player's lack of focus" → 1 条
  'A post from Adam' → 1 条
  'A pouch'  → 1 条
  'A private fantasy' → 1 条
  'A promise to leave the bar.' → 1 条
  'A purse.' → 1 条
  'A raccoon.' → 1 条
  'A rack of assorted animal hair whips' → 1 条
  "A reference to things different yet similar in Howard's world" → 1 条
  'A renewed sense of independence.' → 1 条
  'A robbery' → 1 条
  'A romantic partner' → 1 条
  'A rope'   → 1 条
  'A school uniform' → 1 条
  'A screen is shown.' → 1 条
  'A sculpture' → 1 条
  'A service chute' → 1 条
  'A set of blinds' → 1 条
  'A shared meal.' → 1 条
  "A shockwave emanates from the furnace, causing Sarah to be thrown back, while black smoke pours from Doris' mouth." → 1 条
  'A small pouch.' → 1 条
  'A smart police uniform' → 1 条
  'A smoking curling iron protrudes from her mouth.' → 1 条
  'A sound at an unsual time' → 1 条
  'A space suit.' → 1 条
  'A starlit sky' → 1 条
  'A stick'  → 1 条
  'A stole'  → 1 条
  'A stranger' → 1 条
  "A student's unique ballet performance." → 1 条
  'A study with a bee habitat' → 1 条
  'A stuffed bird' → 2 条
  'A sultry look' → 1 条
  'A suspicious bulge' → 1 条
  'A taser.' → 1 条
  'A tea laced with poison.' → 1 条
  'A teacher intervenes to stop the fight.' → 1 条
  'A teacup' → 1 条
  'A trash bin' → 1 条
  'A trash bin.' → 1 条
  'A tree branch snaps.' → 1 条
  'A turkey leg' → 1 条
  'A vase of flowers' → 1 条
  'A vehicle for stealing picnic baskets' → 1 条
  'A vibrator' → 1 条
  'A vodka bottle.' → 1 条
  'A wallet' → 1 条
  'A watch'  → 1 条
  'A watch, to tell time' → 1 条
  'A wedding ring' → 1 条
  'A whip'   → 1 条
  'A wire'   → 2 条
  'A worm'   → 1 条
  'A worm emerges from his nostril.' → 1 条
  'Above them' → 1 条
  'Accelerate away, or the shark will catch Maya.' → 1 条
  'Accquitances' → 1 条
  'Acquaintances' → 1 条
  'Across the sand dunes' → 1 条
  'Acting'   → 1 条
  'Activate the paw scan, or the door will not open.' → 1 条
  'Adam'     → 1 条
  'Adam posts pictures, Val posts a message, Jess sends a Skype message.' → 1 条
  'Adds a touch of humor' → 1 条
  'Adds a touch of humour' → 1 条
  'Administers an EpiPen' → 1 条
  'Affectionate' → 1 条
  'Afghan hounds' → 1 条
  'Afternoon' → 1 条
  'Against the stone slab' → 1 条
  'Against the vanity' → 1 条
  'Against the wall' → 1 条
  'Age'      → 1 条
  'Agent Butch' → 1 条
  'Aggressively' → 1 条
  'Agile and crab-like' → 1 条
  'Agitated to panic' → 1 条
  'Aim and fire the harpoon, or the shark will escape.' → 1 条
  'Aim his gun, or Jack will kill Anna' → 1 条
  'Aja wakes and Shaina listens.' → 1 条
  'Aja wakes up, and Shaina listens.' → 1 条
  'Alex is not there.' → 1 条
  'Alex is scared, and her father is amused.' → 1 条
  'Alex moves closer to Robbie, Robbie runs out, cut to black.' → 1 条
  "Alex's father" → 1 条
  "Alex's room" → 1 条
  'Alex.'    → 2 条
  'Alice'    → 1 条
  'All A, B and C' → 1 条
  'All of the above' → 10 条
  'All of the above.' → 1 条
  'Allows her to escape the shark' → 1 条
  'Allows him to enter a secret room' → 1 条
  'Allows them to practice aiming at moving targets' → 1 条
  'Amanda becomes angry, and Chris is scared.' → 1 条
  'Amanda recounts a painful past event, linking it to her current insistence.' → 1 条
  'Amanda slaps her mother.' → 1 条
  'Amanda\'s mother calls her a "sweetie."' → 1 条
  "Amanda's story about her mother" → 1 条
  'Amused'   → 2 条
  'Amusement' → 1 条
  'An American flag waves in front of rows of white gravestones.' → 1 条
  'An EpiPen' → 2 条
  'An EpiPen for allergic reaction.' → 1 条
  'An amalgamation of serene acceptance and inevitable closure' → 1 条
  'An application' → 1 条
  'An empty space' → 1 条
  'An engraved stone' → 1 条
  'An explanation' → 1 条
  'An injured person' → 1 条
  'An operations room' → 1 条
  'An operations room.' → 1 条
  'An ultrasound monitor' → 1 条
  'An unidentified character' → 1 条
  'Anastasia' → 1 条
  'Anastasia asserts dominance over Gia.' → 1 条
  'Anastasia confronts Gia about her behavior.' → 1 条
  'Anger'    → 9 条
  'Anger and betrayal, feeling that the pregnancy is a personal affront.' → 1 条
  'Angry'    → 19 条
  'Angry and aggressive' → 1 条
  'Animal motif graffiti' → 1 条
  'Animal motif graffiti on the walls' → 1 条
  'Animated equations' → 1 条
  'Anna'     → 2 条
  'Anna drops her purse and coat, tries a light switch, and turns on a lamp.' → 1 条
  'Anna enters the office, apologizes, and sits down.' → 1 条
  'Anna is confrontational, while Christian is ignorant.' → 1 条
  'Anna is excited, while Christian is hesitant.' → 1 条
  'Anna is serious, and Jack is amused.' → 1 条
  'Anna is shocked, and Lila is submissive.' → 1 条
  'Anna is standing in front of Christian.' → 1 条
  'Anna is standing, Jack is standing' → 1 条
  'Anna is terrified, while Mia is defiant' → 1 条
  'Anna looks out the back window, the SUV crosses railroad tracks, Anna glances out the windshield' → 1 条
  'Anna shoots Jack in the leg.' → 1 条
  "Anna visits the doctor, learns she's pregnant, and tells Christian." → 1 条
  "Anna's pregnancy news" → 1 条
  'Anna\'s request for a "vanilla relationship"' → 1 条
  'Annoyed'  → 3 条
  "Answer Sarah's question, or she will be ignored." → 1 条
  'Answers immediately' → 1 条
  'Anxious'  → 4 条
  'Anxious and concerned' → 1 条
  'Anxious and distracted' → 1 条
  'Anxious and hesitant' → 1 条
  'Anxious loyalty' → 1 条
  'Anxious to calm' → 1 条
  'Anxious to excited' → 2 条
  'Anxious.' → 1 条
  'Apologetic' → 4 条
  'Apologize to Charlie, or he will never forgive her' → 1 条
  'Apologizes' → 1 条
  'Apologizing' → 1 条
  'Applauding' → 1 条
  'Applying lipstick on Layla' → 1 条
  'Approaches her' → 1 条
  "Argues that it's too blurry to make out any details." → 1 条
  'Arlington National Cemetery' → 2 条
  'Arrow'    → 1 条
  'Arthur experiences a series of events that blur the line between reality and imagination.' → 1 条
  'Arthur is emotional, and Hobson is encouraging.' → 1 条
  "Arthur scrambles out of bed. Arthur looks at a wide-eyed man in brown. Hobson sits on Arthur's bed. Hobson fixes Arthur with his steely gaze. Arthur's eyes bulge." → 1 条
  'Arthur tries to establish camaraderie with Fairchild as a way to cope with missing Hobson.' → 1 条
  'As a stone-cold fox.' → 1 条
  'As a symbol of his power' → 1 条
  'As a weapon' → 1 条
  'As contestants' → 1 条
  'As employer-employee' → 1 条
  'As ex-lovers' → 1 条
  'As neighborhood friends' → 1 条
  'As strangers at the aquarium' → 1 条
  'Asks about Mrs. Bark' → 1 条
  'Assertive' → 1 条
  'Asteroid hurtles towards Earth, Sherman plants explosive, Sherman detonates explosive, Asteroid explodes' → 1 条
  "At Burke's place" → 1 条
  'At Lucinda the cat' → 1 条
  "At Sam's group" → 1 条
  'At a cemetery, making the conversation somber.' → 1 条
  'At home'  → 3 条
  'At the French doors' → 1 条
  'At the Hammerhead Club' → 1 条
  'At the airport' → 1 条
  'At the camp' → 1 条
  'At the dining table' → 1 条
  'At the fireplace' → 1 条
  'At the gate' → 1 条
  'At the ground floor' → 1 条
  'At the man-whore union' → 1 条
  "At the shark's dorsal fin" → 1 条
  'At the theater door' → 1 条
  'At the theater door.' → 1 条
  'Attaches a rope to his trousers' → 1 条
  'Attempts to identify the source of the shaking' → 1 条
  'Aunt Bailey' → 2 条
  'Authoritative' → 1 条
  'Ava admires the fish painting, then they enter the aquarium.' → 1 条
  'Away from Charlie' → 1 条
  'Away from Gia' → 1 条
  'Awkward.' → 1 条
  'Back into the tank' → 1 条
  'Back window' → 1 条
  'Backs away' → 1 条
  'Baffled'  → 1 条
  'Bandage his head, or it will get infected.' → 1 条
  'Barb'     → 2 条
  "Barb finds Sharif's body, opens the door, and finds the girl." → 1 条
  "Barb is calm, the girl doesn't interact with the body." → 1 条
  'Barb is indifferent, Willis is concerned.' → 1 条
  'Barb must descend on a wire from the window, or she and the girl will be caught.' → 1 条
  "Barb taking keys from Sharif's body" → 1 条
  'Base'     → 1 条
  'Battered and upside down' → 1 条
  'Beaver'   → 1 条
  'Because she unleashed hell on the world' → 1 条
  'Becomes grateful' → 1 条
  'Becomes hairless' → 1 条
  'Becomes more apologetic' → 1 条
  'Becomes more confrontational' → 1 条
  'Becomes more distant' → 1 条
  'Becomes more excited' → 1 条
  'Becomes more sympathetic' → 1 条
  'Behind'   → 1 条
  'Behind Maya' → 2 条
  'Behind the board.' → 1 条
  'Behind the warehouse' → 1 条
  'Being lost in her thoughts' → 1 条
  'Being thrown to the back of the shuttle' → 1 条
  'Being violent' → 1 条
  'Bella accepts it, and Jacob leaves.' → 1 条
  'Bella argues with him' → 1 条
  'Bella confesses her love to Jake.' → 1 条
  'Bella cutting her finger' → 2 条
  'Bella drops her gaze.' → 1 条
  'Bella enters, slaps the young man, Paul transforms into a wolf.' → 1 条
  'Bella falls, Jacob helps, Jacob worries.' → 1 条
  'Bella is calm, Jacob is worried.' → 1 条
  'Bella is calm, and Edward is concerned.' → 1 条
  'Bella is determined, and Edward is reluctant.' → 1 条
  'Bella is sad, Edward is angry' → 1 条
  'Bella is sad, Edward is conflicted.' → 1 条
  'Bella is sitting on her bed.' → 1 条
  'Bella pleads with Felix to kill her, while Arrow motions for Felix to wait.' → 1 条
  'Bella remembers the story, and Jacob is relieved.' → 1 条
  'Bella slaps him, and Paul holds him back.' → 1 条
  'Bella slaps the young man.' → 1 条
  'Bella smiles, then slices her finger on the wrapping.' → 1 条
  'Bella tries to stop Jacob from leaving.' → 1 条
  "Bella's decision to ride the bike again" → 1 条
  "Bella's injury" → 1 条
  "Bella's insistence on becoming like Edward" → 1 条
  "Bella's slap" → 1 条
  'Ben argues with his father' → 1 条
  'Ben calls out "Alex."' → 1 条
  'Ben climbs faster, Kim covers her face.' → 1 条
  'Ben walks towards the stairs, looks in Alex\'s room, and calls out "Alex."' → 1 条
  'Bender knocks over his table, rushes to the girls, and hisses at them.' → 1 条
  'Benter'   → 1 条
  'Beside him' → 1 条
  'Beside it' → 1 条
  'Beverly'  → 1 条
  'Beverly runs her fingers through his plumage, drapes a blanket over him, and finds his wallet.' → 1 条
  'Beverly starts to feel more comfortable and open.' → 1 条
  'Bill'     → 2 条
  'Bill and Everett' → 1 条
  'Billy hits Charlie' → 1 条
  'Billy.'   → 1 条
  'Birds look better when stuffed due to their passive nature.' → 1 条
  'Bites him' → 1 条
  'Bites his groin' → 1 条
  'Black'    → 11 条
  'Black and white' → 1 条
  'Black confronts Manuel and Black shoots Manuel.' → 1 条
  'Black confronts Manuel, Black shoots Manuel, Manuel stabs Black.' → 1 条
  'Black is calm and Manuel is scared.' → 1 条
  'Black liquid' → 1 条
  'Black telling Mr. Emil about loose end' → 1 条
  'Blaine Polda' → 1 条
  'Blaine communicates with the entity.' → 1 条
  'Blaine puts on the gas mask, kicks the table, and acts to communicates with the entity.' → 1 条
  'Blair'    → 1 条
  'Blair calls the police, Blair types the address, Blair sends the address.' → 1 条
  'Blair is relieved, Jess is scared.' → 1 条
  'Blair requests her help' → 1 条
  'Blocks his path' → 1 条
  'Blonde'   → 3 条
  'Bloody'   → 1 条
  'Blows a dart into it' → 1 条
  'Blows it out' → 1 条
  'Blue'     → 8 条
  'Blue crystals' → 1 条
  'Bob their heads' → 1 条
  'Bobby J cheats, Ben climbs the tree, a branch snaps, Ben punches the button, and Lance flings the grease can.' → 1 条
  'Body shape' → 1 条
  "Bomb discovery, Queen's safety, bomb defusal" → 1 条
  'Boo-Boo'  → 1 条
  "Boo-Boo's motivational speech" → 3 条
  'Both Charlie and Phil reject.' → 1 条
  'Both Gus and Old Deuteronomy are amused.' → 1 条
  'Both Kitty Eagle-O and little scrumptious are excited.' → 1 条
  'Both Mr. Ranger and Yogi are sad.' → 1 条
  'Both Taylor and Christian' → 1 条
  'Bottle'   → 1 条
  'Bounces on a rubber ring' → 1 条
  'Bouncing on a rubber ring' → 1 条
  'Bow to Brian, or he will punish her.' → 1 条
  'Bows'     → 1 条
  'Brandon explains he was burying his condor.' → 1 条
  'Brandon ruins the condor, May enters with a cake, May finds dirt on the sweater.' → 1 条
  'Break off the kiss, or he will lose control.' → 1 条
  'Brenda'   → 1 条
  'Brian'    → 1 条
  'Brian interacts with Riley about her defiance.' → 1 条
  'Brian winks at Riley' → 1 条
  'Brian winks, Riley dances, Chris steps forward' → 1 条
  'Brightens' → 1 条
  "Brings her hands to her face, gazes out at the city, crosses the room, lies down in bed, sits up quickly, glances at Christian's empty side of the bed, makes a phone call, sits on the couch by the fireplace, and lies down on the couch" → 1 条
  'Broken'   → 1 条
  'Brothers' → 1 条
  'Brown'    → 1 条
  'Bruised'  → 1 条
  'Brunette' → 1 条
  'Brushing eye shadow' → 1 条
  'Buck is defensive, and Charlie is accusatory.' → 1 条
  'Buck is more defensive than Charlie.' → 1 条
  'Buck is retiring' → 1 条
  'Buck is sitting on a bench, Charlie is standing in front of him.' → 1 条
  'Buck takes a deep breath.' → 1 条
  'Buck, who hangs his arm over the back of the bench and looks away.' → 1 条
  'Burke'    → 1 条
  'Burke feels his way along the piano, Julia crawls under it, Burke blocks her path.' → 1 条
  'Burke is standing in front of Julia.' → 1 条
  'Burke is surprised, Julia is scared.' → 1 条
  'Burke turns and faces the window.' → 1 条
  "Burke's grin fades." → 1 条
  'Burly men' → 1 条
  'Burning'  → 2 条
  'Bury his condor, or it will decompose.' → 1 条
  'Butch puts his paw on the door.' → 1 条
  'Buttons a cloak' → 1 条
  'By agreeing with Anna' → 1 条
  'By appealing to her emotions' → 1 条
  'By asking questions' → 1 条
  'By attacking him' → 1 条
  'By clearly demanding Gia stop speaking to Christian as if she were not present and asserting her own authority.' → 1 条
  'By demonstrating that the accused is a doppelganger and not Moriarty.' → 1 条
  'By explaining that the shaking is caused by a truck passing by' → 1 条
  'By explicitly telling Gia to stop making eyes at Christian and to refer to her as "Mrs. Gray."' → 1 条
  'By highlighting her authority through subtle cues' → 1 条
  'By inviting him to sit down' → 1 条
  'By making a joke about CNN' → 1 条
  'By offering a token of peace in exchange for their flag' → 1 条
  'By saying "you need help"' → 1 条
  'By sending messages' → 1 条
  'By standing close to him' → 1 条
  'By ultralight aircraft' → 1 条
  'By unleashing a devastating sound' → 1 条
  'By using a stage prop as a weapon' → 1 条
  'By using a wire to descend from a window' → 1 条

In [ ]:
# 运行这段诊断，查看实际的 question_category 值分布
from datasets import load_dataset
from collections import Counter

# dataset = load_dataset('tomg-group-umd/cinepile', split='test')

counter = Counter(dataset[i]['question_category'] for i in range(200))
print("=== question_category 实际值分布 ===")
for val, cnt in sorted(counter.items(), key=lambda x: -x[1]):
    print(f"  {cnt:4d}  {repr(val)}")

=== question_category 实际值分布 ===
    88  'Character and\nRelationship Dynamics'
    63  'Setting and\nTechnical Analysis'
    24  'Temporal'
    13  'Narrative and\nPlot Analysis'
    12  'Theme Exploration'

In [ ]:
# 快速验证（无需重新加载数据集）
test_categories = [
    'Character and\nRelationship Dynamics',
    'Setting and\nTechnical Analysis',
    'Temporal',
    'Narrative and\nPlot Analysis',
    'Theme Exploration',
]

category_map = {
    'TEMP': 'Temporal',
    'CRD':  'Character and',
    'NPA':  'Narrative and',
    'STA':  'Setting and',
    'TH':   'Theme Exploration',
}

import pandas as pd
df_test = pd.DataFrame({'question_category': test_categories})

print("=== 映射验证 ===")
for abbr, keyword in category_map.items():
    mask = df_test['question_category'].str.contains(keyword, case=False, na=False)
    matched = df_test.loc[mask, 'question_category'].tolist()
    print(f"  {abbr} ({keyword!r:20s}) → {matched}")

=== 映射验证 ===
  TEMP ('Temporal'          ) → ['Temporal']
  CRD ('Character and'     ) → ['Character and\nRelationship Dynamics']
  NPA ('Narrative and'     ) → ['Narrative and\nPlot Analysis']
  STA ('Setting and'       ) → ['Setting and\nTechnical Analysis']
  TH ('Theme Exploration' ) → ['Theme Exploration']

# Vt=50

In [ ]:


# ================= 1. 配置 =================

@dataclass
class PrefixConfig:
    dataset_name: str          = "tomg-group-umd/cinepile"
    train_split: str           = "train"
    test_split: str            = "test"

    max_train_samples: Optional[int] = 20000
    max_test_samples: Optional[int]  = None
    hard_oversample_ratio: float     = 1.5

    base_model_id: str         = "meta-llama/Llama-3.1-8B-Instruct"

    max_scene_length: int      = 1000
    max_seq_length: int        = 1024

    num_train_epochs: int      = 3
    per_device_train_batch_size: int = 4
    gradient_accumulation_steps: int = 4
    learning_rate: float       = 5e-4
    warmup_ratio: float        = 0.05
    lr_scheduler_type: str     = "cosine"
    bf16: bool                 = True
    logging_steps: int         = 50

    output_dir: str            = "./prefix_cinepile"
    log_path: str              = "./prefix_experiment_log.csv"

    prefix_num_virtual_tokens: int = 50

    max_new_tokens: int        = 5

    category_map: Dict[str, str] = field(default_factory=lambda: {
        "TEMP": "Temporal",
        "CRD":  "Character and",
        "NPA":  "Narrative and",
        "STA":  "Setting and",
        "TH":   "Theme Exploration",
    })

    seed: int                  = 42


# ================= 2. Stratified Sampler + DATASET =================

class StratifiedSampler:
    def __init__(self, cfg: PrefixConfig):
        self.cfg = cfg

    def sample(self, data):
        if self.cfg.max_train_samples is None:
            print(f"[Sampler] Using full train split: {len(data)} samples")
            return data

        target = self.cfg.max_train_samples
        groups = defaultdict(list)

        for s in data:
            cat  = self._get_category_key(s["question_category"])
            hard = bool(s["hard_split"])
            groups[(cat, hard)].append(s)

        n_categories = len(set(k[0] for k in groups))
        base_quota   = target / (n_categories * (1 + self.cfg.hard_oversample_ratio))
        easy_q       = base_quota
        hard_q       = base_quota * self.cfg.hard_oversample_ratio

        sampled = []
        report  = []

        import random
        random.seed(self.cfg.seed)

        for (cat, hard), group in sorted(groups.items()):
            quota  = int(hard_q if hard else easy_q)
            n_take = min(quota, len(group))
            taken  = random.sample(group, n_take)
            sampled.extend(taken)
            report.append({
                "category":  cat,
                "hard":      hard,
                "available": len(group),
                "quota":     quota,
                "sampled":   n_take,
            })

        if len(sampled) < target:
            sampled_ids = set(id(s) for s in sampled)
            remaining   = [s for s in data if id(s) not in sampled_ids]
            extra = random.sample(
                remaining, min(target - len(sampled), len(remaining))
            )
            sampled.extend(extra)

        df = pd.DataFrame(report)
        print("\n[Sampler] ===== Stratified Sampling Report =====")
        print(df.to_string(index=False))
        print(f"[Sampler] Total sampled: {len(sampled)}")
        print("[Sampler] " + "=" * 60)
        return sampled

    def _get_category_key(self, cat_str: str) -> str:
        for abbr, kw in self.cfg.category_map.items():
            if kw.lower() in cat_str.lower():
                return abbr
        return "OTHER"


class CinePileDataset:
    LETTERS = ["A", "B", "C", "D", "E"]

    def __init__(self, cfg: PrefixConfig, seen_ids: Optional[Set[int]] = None):
        self.cfg      = cfg
        self.seen_ids = seen_ids or set()
        self.train_data, self.test_data = self._load_all()
        print(f"[Dataset] Train: {len(self.train_data)} | Test: {len(self.test_data)}")

    @classmethod
    def _answer_text_to_letter(cls, answer_text: str, choices: list) -> str:
        for i, c in enumerate(choices):
            if answer_text.strip() == c.strip():
                return cls.LETTERS[i]
        for i, c in enumerate(choices):
            if answer_text.strip() in c or c.strip() in answer_text:
                return cls.LETTERS[i]
        return "A"

    @staticmethod
    def _normalize_hard_split(raw) -> bool:
        if isinstance(raw, bool):
            return raw
        return str(raw).strip().lower() == "true"

    def _load_split(self, split: str):
        raw = load_dataset(self.cfg.dataset_name, split=split)
        samples = []
        for idx, ex in enumerate(raw):
            letter = self._answer_text_to_letter(ex["answer_key"], ex["choices"])
            samples.append({
                "sample_id":         idx,
                "movie_scene":       ex["movie_scene"],
                "question":          ex["question"],
                "choices":           ex["choices"],
                "answer_key":        letter,
                "question_category": ex["question_category"],
                "hard_split":        self._normalize_hard_split(ex["hard_split"]),
            })
        return samples

    def _load_all(self):
        train_raw = self._load_split(self.cfg.train_split)
        test_raw  = self._load_split(self.cfg.test_split)

        if self.seen_ids:
            before = len(train_raw)
            train_raw = [s for s in train_raw if s["sample_id"] not in self.seen_ids]
            print(f"[Dataset] Filtered seen samples: {before} → {len(train_raw)}")

        sampler    = StratifiedSampler(self.cfg)
        train_data = sampler.sample(train_raw)

        if self.cfg.max_test_samples:
            test_data = test_raw[:self.cfg.max_test_samples]
        else:
            test_data = test_raw

        return train_data, test_data


# ================= 3. Prompt and Evaluator =================

class PromptBuilder:
    @staticmethod
    def build_train_prompt(sample: dict, max_scene_length: int) -> str:
        scene   = sample["movie_scene"][:max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample["choices"])
        )
        return (
            "You are watching a movie. Based on the scene description, "
            "answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            f"Answer: {sample['answer_key']}"
        )

    @staticmethod
    def build_inference_prompt(sample: dict, max_scene_length: int) -> str:
        scene   = sample["movie_scene"][:max_scene_length]
        options = "\n".join(
            f"{chr(65+i)}. {c}" for i, c in enumerate(sample["choices"])
        )
        return (
            "You are watching a movie. Based on the scene description, "
            "answer the multiple choice question.\n\n"
            f"Scene: {scene}\n\n"
            f"Question: {sample['question']}\n\n"
            f"Options:\n{options}\n\n"
            "Answer:"
        )


class Evaluator:
    def __init__(self, cfg: PrefixConfig):
        self.cfg = cfg

    def evaluate(self, model, tokenizer, test_data: list) -> dict:
        model.eval()
        device = next(model.parameters()).device
        records = []
        for s in tqdm(test_data, desc="Eval Prefix"):
            pred = self._predict(model, tokenizer, s, device)
            records.append({
                "pred":              pred,
                "label":             s["answer_key"],
                "question_category": s["question_category"],
                "hard_split":        s["hard_split"],
            })
        df = pd.DataFrame(records)
        return self._compute_metrics(df)

    def _predict(self, model, tokenizer, sample: dict, device: torch.device) -> str:
        prompt = PromptBuilder.build_inference_prompt(sample, self.cfg.max_scene_length)
        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=self.cfg.max_seq_length,
        ).to(device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=self.cfg.max_new_tokens,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
            )
        decoded = tokenizer.decode(
            outputs[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True,
        ).strip().upper()

        for ch in decoded:
            if ch in "ABCDE":
                return ch
        return "A"

    def _compute_metrics(self, df: pd.DataFrame) -> dict:
        correct = df["pred"] == df["label"]
        metrics = {"Overall": correct.mean(), "Overall_n": len(df)}
        for abbr, keyword in self.cfg.category_map.items():
            mask = df["question_category"].str.contains(keyword, case=False, na=False)
            n    = int(mask.sum())
            metrics[abbr]        = correct[mask].mean() if n > 0 else None
            metrics[f"{abbr}_n"] = n
        hard_mask = df["hard_split"] == True
        n_hard    = int(hard_mask.sum())
        metrics["Hard"]   = correct[hard_mask].mean() if n_hard > 0 else None
        metrics["Hard_n"] = n_hard
        return metrics


# ================= 4. Prefix Trainer =================

class PrefixTrainer:
    def __init__(self, cfg: PrefixConfig):
        self.cfg       = cfg
        self.model     = None
        self.tokenizer = None

    def _output_dir(self) -> str:
        os.makedirs(self.cfg.output_dir, exist_ok=True)
        return self.cfg.output_dir

    def _make_hf_dataset(self, data: list) -> Dataset:
        return Dataset.from_list([
            {"text": PromptBuilder.build_train_prompt(s, self.cfg.max_scene_length)}
            for s in data
        ])

    def _load_base_model_bf16(self):
        tokenizer = AutoTokenizer.from_pretrained(self.cfg.base_model_id)
        tokenizer.pad_token    = tokenizer.eos_token
        tokenizer.padding_side = "right"
        model = AutoModelForCausalLM.from_pretrained(
            self.cfg.base_model_id,
            torch_dtype=torch.bfloat16,
            device_map="auto",
        )
        return model, tokenizer

    def train(self, train_data: list):
        print(f"\n[Prefix] Loading base model (bf16)...")
        model, tokenizer = self._load_base_model_bf16()

        prefix_config = PrefixTuningConfig(
            task_type          = TaskType.CAUSAL_LM,
            num_virtual_tokens = self.cfg.prefix_num_virtual_tokens,
            prefix_projection  = True,
        )
        model = get_peft_model(model, prefix_config)
        model.print_trainable_parameters()

        args = SFTConfig(
            output_dir                  = self._output_dir(),
            num_train_epochs            = self.cfg.num_train_epochs,
            per_device_train_batch_size = self.cfg.per_device_train_batch_size,
            gradient_accumulation_steps = self.cfg.gradient_accumulation_steps,
            learning_rate               = self.cfg.learning_rate,
            warmup_ratio                = self.cfg.warmup_ratio,
            lr_scheduler_type           = self.cfg.lr_scheduler_type,
            bf16                        = self.cfg.bf16,
            logging_steps               = self.cfg.logging_steps,
            save_strategy               = "no",
            max_length                  = self.cfg.max_seq_length,
            dataset_text_field          = "text",
            report_to                   = "none",
            gradient_checkpointing      = False,
        )

        hf_dataset = self._make_hf_dataset(train_data)
        trainer = SFTTrainer(
            model            = model,
            args             = args,
            train_dataset    = hf_dataset,
            processing_class = tokenizer,
        )

        print(f"[Prefix] Training on {len(train_data)} samples...")
        trainer.train()

        log_history = trainer.state.log_history
        if len(log_history) > 0:
            df_log  = pd.DataFrame(log_history)
            log_path = os.path.join(self._output_dir(), "training_log_history.csv")
            df_log.to_csv(log_path, index=False)
            print(f"[Prefix] Step-wise log saved → {log_path}")

        trainer.save_model(self._output_dir())
        tokenizer.save_pretrained(self._output_dir())
        print(f"[Prefix] Saved adapter → {self._output_dir()}")

        self.model     = trainer.model
        self.tokenizer = tokenizer

    def free_memory(self):
        if self.model is not None:
            del self.model
        if self.tokenizer is not None:
            del self.tokenizer
        self.model = None
        self.tokenizer = None
        gc.collect()
        torch.cuda.empty_cache()


# ================= 5. main =================

if __name__ == "__main__":
    import transformers
    print("transformers:", transformers.__version__)

    # Removed duplicate drive.mount() call as it's already mounted.
    # from google.colab import drive
    # drive.mount('/content/drive')

    import os
    PROJECT_DIR = "/content/drive/MyDrive/266_final/phase2/CinePile_Prefix"
    os.makedirs(PROJECT_DIR, exist_ok=True)
    print("Project dir:", PROJECT_DIR)

    cfg = PrefixConfig(
        base_model_id         = "meta-llama/Llama-3.1-8B-Instruct",
        max_train_samples     = 30000,
        max_test_samples      = None,
        hard_oversample_ratio = 1.5,
        num_train_epochs      = 3,
        per_device_train_batch_size = 4,
        gradient_accumulation_steps = 4,
        learning_rate         = 5e-4,
        output_dir            = os.path.join(PROJECT_DIR, "prefix_cinepile"),
        log_path              = os.path.join(PROJECT_DIR, "prefix_experiment_log.csv"),
    )

    used_ids_path = os.path.join(PROJECT_DIR, "used_sample_ids_prefix.txt")

    set_seed(cfg.seed)

    # read sample_ids
    seen_ids: Set[int] = set()
    if os.path.exists(used_ids_path):
        with open(used_ids_path, "r") as f:
            for line in f:
                try:
                    seen_ids.add(int(line.strip()))
                except:
                    pass
        print(f"[UsedIDs] Prefix loaded {len(seen_ids)} seen ids from {used_ids_path}")

    dataset   = CinePileDataset(cfg, seen_ids=seen_ids)
    evaluator = Evaluator(cfg)
    trainer   = PrefixTrainer(cfg)

    trainer.train(dataset.train_data)
    metrics = evaluator.evaluate(trainer.model, trainer.tokenizer, dataset.test_data)

    print("\n[Prefix] ===== Eval Metrics =====")
    for k, v in metrics.items():
        if not k.endswith("_n") and v is not None:
            n = metrics.get(f"{k}_n", "")
            print(f"  {k:<10}: {v:.2%}  (n={n})")

    pd.DataFrame([metrics]).to_csv(
        os.path.join(cfg.output_dir, "prefix_metrics.csv"), index=False
    )

    # record the used sample_id
    with open(used_ids_path, "a") as f:
        for s in dataset.train_data:
            f.write(str(s["sample_id"]) + "\n")
    print(f"[UsedIDs] Prefix appended {len(dataset.train_data)} ids → {used_ids_path}")

    trainer.free_memory()

transformers: 5.0.0
Project dir: /content/drive/MyDrive/266_final/phase2/CinePile_Prefix

README.md: 0.00B [00:00, ?B/s]

v2/train-00000-of-00003.parquet:   0%|          | 0.00/21.9M [00:00<?, ?B/s]

v2/train-00001-of-00003.parquet:   0%|          | 0.00/23.2M [00:00<?, ?B/s]

v2/train-00002-of-00003.parquet:   0%|          | 0.00/23.3M [00:00<?, ?B/s]

v2/test-00000-of-00001.parquet:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/298888 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/4941 [00:00<?, ? examples/s]

[Sampler] ===== Stratified Sampling Report =====
category  hard  available  quota  sampled
     CRD False     127468   2400     2400
     NPA False      32238   2400     2400
     STA False      85604   2400     2400
    TEMP False      41517   2400     2400
      TH False      12061   2400     2400
[Sampler] Total sampled: 30000
[Sampler] ============================================================
[Dataset] Train: 30000 | Test: 4941

[Prefix] Loading base model (bf16)...

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 68,275,200 || all params: 8,098,536,448 || trainable%: 0.8431

Adding EOS to train dataset:   0%|          | 0/30000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/30000 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 128009}.

[Prefix] Training on 30000 samples...

[Prefix] Step-wise log saved → /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/prefix_cinepile/training_log_history.csv
[Prefix] Saved adapter → /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/prefix_cinepile

Eval Prefix:   0%|          | 0/4941 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
/usr/local/lib/python3.12/dist-packages/peft/peft_model.py:2141: UserWarning: Position ids are not supported for parameter efficient tuning. Ignoring position ids.
  warnings.warn("Position ids are not supported for parameter efficient tuning. Ignoring position ids.")
Eval Prefix: 100%|██████████| 4941/4941 [07:18<00:00, 11.26it/s]

[Prefix] ===== Eval Metrics =====
  Overall   : 61.85%  (n=4941)
  TEMP      : 45.93%  (n=688)
  CRD       : 64.36%  (n=2068)
  NPA       : 63.71%  (n=463)
  STA       : 65.01%  (n=1532)
  TH        : 62.11%  (n=190)
  Hard      : 41.94%  (n=887)
[UsedIDs] Prefix appended 30000 ids → /content/drive/MyDrive/266_final/phase2/CinePile_Prefix/used_sample_ids_prefix.txt